apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    component: mongo-express
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: gcr.io/plural-computing/mongo-express:latest
        imagePullPolicy: Always
        env:
        - name: ENVIRONMENT
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: VCAP_APP_PORT
          value: '1234'
        - name: ME_CONFIG_MONGODB_SERVER
          value: 'mgo-replicaset'
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mgo-replicaset-auth
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mgo-replicaset-auth
              key: password